apiVersion: v1
kind: Service
metadata:
  name: industrial-planner-backend
  labels:
    app.kubernetes.io/name: industrial-planner-backend
spec:
  selector:
    app.kubernetes.io/name: industrial-planner-backend
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
